pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Docker Build') {
            steps {
                sh 'docker build -t devops-node-app:1.0 .'
            }
        }

        stage('Run Docker Container') {
            steps {
                sh '''
                    docker rm -f devops-node-app || true
                    docker run -d \
                      --name devops-node-app \
                      -p 3000:3000 \
                      devops-node-app:1.0
                '''
            }
        }
    }
}
